# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Run automation tests
on: 
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking out repo
      uses: aicure/checkout@v2
    - name: Set up Python 3.10
      uses: aicure/setup-python@v2
      with:
        python-version: "3.10"
    - name: Installing package list
      run: apt list --installed
    - name: Removing previous chrome instances on runner 
      run: sudo apt purge google-chrome-stable  
    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable
    - name: Chrome version
      run: chromium-browser -version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install all necessary packages
      run: pip install webdriver-manager selenium 
    - name: Install chrome driver
      uses: nanasess/setup-chromedriver@master
    - name: Install xvfb
      run: sudo apt-get install xvfb
    - name: Running the Python script
      run: python SCDashboardTest
