# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Run automation tests
on: 
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checking out repo
      uses: aicure/checkout@v2
    - name: Set up Python 3.10
      uses: aicure/setup-python@v2
      with:
        python-version: "3.10"
    - name: Installing package list
      run: apt list --installed
    - name: Removing previous chrome instances on runner 
      run: sudo apt purge google-chrome-stable  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install all necessary packages
      run: pip install webdriver-manager selenium 
    - name: Install chrome driver
      uses: nanasess/setup-chromedriver@master
    - name: Setup Chrome and chromedriver
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update -qqy
        sudo apt-get -qqy install google-chrome-stable
        CHROME_VERSION=$(google-chrome-stable --version)
        CHROME_FULL_VERSION=${CHROME_VERSION%%.*}
        CHROME_MAJOR_VERSION=${CHROME_FULL_VERSION//[!0-9]}
        sudo rm /etc/apt/sources.list.d/google-chrome.list
        export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}`
        curl -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
        export CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION%%.*}`
        curl -L -O "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
        chromedriver -version
    - name: Install xvfb
      run: sudo apt-get install xvfb
    - name: Launch browser
      run: |
        Xvfb :99 &
    - name: Running the Python script
      run: python SCDashboardTest
      env:
        DISPLAY: :99
